version: "3.8"

services:
  portainer-ce:
    container_name: main-portainer
    image: portainer/portainer-ce:latest
    restart: always
    expose:
      - "8000"
      - "9000"
      - "9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
      - /etc/localtime:/etc/localtime:ro 
    networks:
      - main_net

  tunnel:
    container_name: main-cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    env_file:
      - .env
    networks:
      - main_net

  gitlab:
    container_name: main-gitlab
    image: gitlab/gitlab-ee:latest
    restart: always
    hostname: 'gitlab.buildin.kr'
    expose:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    shm_size: '256m'
    networks:
      - main_net

networks:
  main_net:
    driver: bridge
